In [1]:
import pandas as pd
import numpy as np

C:\Users\qf3636ll\AppData\Local\Temp\ipykernel_23404\2162656668.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [2]:
df = pd.read_csv("andOneDayIllDie.csv")

#get rid of 3 digits and - at the beginning of the name
for i in df.index:
    name = df.at[i, 'Item Name']
    name = name.lower()
    name = name.replace("(next gen)","next gen").replace("(next generation)","next gen")
    name = name.replace('hrough','hhough').replace('four','4')
    name = name.replace("hr.","hr").replace("hr.","hr").replace("hrs.","hr").replace("hrs","hr").replace("hours","hr").replace('hour','hr').replace('hro','hho')
    txt3 = name[0]
    txt4 = name[1]
    txt5 = name[2]
    txt6 = name[3]
    txt7 = name[4]
    digit_list = ['0','1','2','3','4','5','6','7','8','9'] #np.arange(1,11)
    if txt3 in digit_list:
        if txt4 in digit_list:
            if txt5 in digit_list:
                if txt6=='-':
                    if txt7 == ' ':
                        r_name = name[5:]
                        df.at[i, 'Item Name'] = r_name
                    else:
                        r_name = name[4:]
                        df.at[i, 'Item Name'] = r_name
                else: df.at[i, 'Item Name'] = name
            else: df.at[i, 'Item Name'] = name
        else: df.at[i, 'Item Name'] = name
    else: df.at[i, 'Item Name'] = name

    
#dealing with time
hr = "hr"
digit_list = ['0','1','2','3','4','5','6','7','8','9','-']
punct_list = [' ','-','.']
for i in df.index:
    name = df.at[i, 'Item Name']
    #name = name.lower()
    #name = name.replace('hrough','hhough').replace('four','4')
    #name = name.replace("hr.","hr").replace("hr.","hr").replace("hrs.","hr").replace("hrs","hr").replace("hours","hr").replace('hour','hr').replace('hr','hr')

    length = ''
    if hr in name:
        dex1 = name.find(hr)
        dex_1 = dex1-1
        dex_2 = dex1-2
        dex_3 = dex1-3
        dex_4 = dex1-4
        dex_5 = dex1-5
        dex_6 = dex1-6
        dig1,dig2,dig3,dig4,dig5,dig6 = name[dex_1],name[dex_2],name[dex_3],name[dex_4],name[dex_5],name[dex_6]
        dex2 = dex1+2
        dig_list = [dig6,dig5,dig4,dig3,dig2,dig1]
        dug = 6
        for dig in dig_list:
            if dig in digit_list+punct_list:
                length=length+dig
            else: continue
        for dig in dig_list:
            if dig in digit_list:
                break
            else:
                dug = dug - 1
        r_length = f'{length}hr'
        remove = name[dex1-dug:dex2]
        r_name = name.replace(remove,'')
        df.at[i,'Item Name'] = r_name
        df.at[i,'Max'] = r_length
    else:
        length = df.at[i,'length']
        alt_length = f'{length}hr__'
        df.at[i,'Max'] = alt_length

for j in df.index:
    name = df.at[j, 'Item Name']
    r_name = name.replace('hhough','hrough').replace('()','')
    df.at[j, 'Item Name'] = r_name
    length = df.at[j, 'Max']
    r_length = length.replace(' ','')
    r_length = r_length.strip('-').strip()
    df.at[j, 'Max'] = r_length

#move everything within () into location
for i in df.index:
    loc_name = ''
    name = df.at[i, 'Item Name']
    #name = name.replace("(Next Gen)","Next Generation").replace("(Next Generation)","Next Generation")
    txt11 = name.find("(")
    txt12 = name.find(")")
    txt13 = name.lower().find("-austin")
    txt14 = name.lower().find("- austin")
    #if there is a -austin
    if txt13 != -1:
        r_name = name[0:txt13]
        df.at[i, 'Item Name'] = r_name
        loc_name2 = name[txt13+1:]
        df.at[i, 'Min'] = loc_name+loc_name2
    #if there is a - austin
    elif txt14 != -1:
        r_name = name[0:txt14]
        df.at[i, 'Item Name'] = r_name
        loc_name2 = name[txt14+2:]
        df.at[i, 'Min'] = loc_name+loc_name2
    #if parentheses exist
    elif txt11 != -1:
        loc_name = name[txt11:txt12+1]
        r_name1 = name[0:txt11]
        r_name2 = name[txt12+1:]
        r_name = r_name1+r_name2
        df.at[i, 'Item Name'] = r_name
        df.at[i, 'Min'] = loc_name
        txt15 = r_name.find("(")
        txt16 = r_name.find(")")
        if txt15 != -1:
            loc_name2 = r_name[txt15:txt16+1]
            r_name3 = r_name[0:txt15]
            r_name4 = r_name[txt16+1:]
            r_name_ = r_name3+r_name4
            df.at[i, 'Item Name'] = r_name_
            df.at[i, 'Min'] = loc_name + loc_name2
        else: continue
    else: continue   
    
    
#get rid of the phrase "SAT AM" or "SAT PM"
for h in df.index:
    name = df.at[h, 'Item Name']
    #txt1 = name.find("SAT AM")
    #txt2 = name.find("SAT PM")
    #txt8 = name.find("SAT/SUN")
    #txt9 = name.find("SUN AM")
    #txt10 = name.find("SUN PM")
    txt1 = name.find(" am")
    txt2 = name.find(" pm")
    txt8 = name.find(" sat")
    txt9 = name.find(" sun")
    
    if txt1 != -1:
        r_name = name[0:txt1]
        df.at[h, 'Item Name'] = r_name
    elif txt2 != -1:
        r_name = name[0:txt2]
        df.at[h, 'Item Name'] = r_name
    elif txt8 != -1:
        r_name = name[0:txt8]
        df.at[h, 'Item Name'] = r_name
    elif txt9 != -1:
        r_name = name[0:txt9]
        df.at[h, 'Item Name'] = r_name
    #elif txt10 != -1:
     #   r_name = name[0:txt10]
     #   df.at[h, 'Item Name'] = r_name
    else:
        continue


#establish Fire as Subject
Fire = pd.DataFrame({"Keyword":["arson","gas","mayday","rtk","extrication","confined","pump"," fd","fire","burn","haz","rescue","rollover","survival","smoke","rigging","scba","emergency","ffi","cribbing","hose","forcible","ventiliation trailer","70e","nfpa","emt","first 5","pd","tactics","training officer"]})
Fire['Subject'] = "FIRE/EMT"
#establish Nursing as Subject
Nursing = pd.DataFrame({"Keyword":["nursing","cna","medication aide","teas","acls","pals","health science"]})
Nursing['Subject'] = "NURSING"
#establish Driving as Subject
Driving = pd.DataFrame({"Keyword":["bus","cdl","foodliner","commercial vehic", "rider","commercial driver"]})
Driving['Subject'] = "DRIVING"
#establish Computers as Subject
Computers = pd.DataFrame({"Keyword":["excel","power point","word","windows","e-mail","merging"]})
Computers['Subject'] = "COMPUTERS"
#establish Leadership as Subject
Leadership = pd.DataFrame({"Keyword":["leader","strengths","strengthsfinder","supervisors","project management"]})
Leadership['Subject'] = "LEADERSHIP"
#establish Industry to include Electricians, welders, manufacturing, regulations as Subject
Industry = pd.DataFrame({"Keyword":["power limited","ceu","plt","arch flash","arc flash","electrical","weld","manufacturing", "wdi","symposium","steam engineering","osha", "storage tank","pain-free","forklift"]})
Industry['Subject'] = "INDUSTRY"
#establish Ethnobotny
Ethnobotony = pd.DataFrame({"Keyword":["fiber","ethno"]})
Ethnobotony['Subject'] = "ETHN"
#establish Cosmetology/massage
Cosmetology = pd.DataFrame({"Keyword":["cosmetology","massage"]})
Cosmetology['Subject'] = "COSMETOLOGY"
#establish Radiography
Radiography = pd.DataFrame({"Keyword":["radiography","mri"]})
Radiography['Subject'] = "RADIOGRAPHY"
#put them all together into one df
keywords = pd.concat([Fire,Nursing,Driving,Computers,Leadership,Industry,Ethnobotony,Cosmetology,Radiography])
keywords.reset_index(inplace=True)
#establish FirstAid as Subject on its own because it is going to be run first
FirstAid = ["american heart association","aha","cpr", "first aid","bls"]

instructors = pd.read_csv("InstructorSubject.csv")
df['Subject'] = np.nan
for w in df.index:
    loc_name = ''
    words = df.at[w, 'Item Name']
    instr = df.at[w, 'instructor'] 
    for kw in FirstAid:
        if kw in words:
            df.at[w,'Subject'] = "FIRST AID"
            break
        else:
            if instr != "na":
                for idex in instructors.index:
                    ins = instructors.at[idex,'Instructor']
                    if ins in instr:
                        df.at[w,'Subject'] = instructors.at[idex,'Subject']
                        break
                    else: continue
            else:
                for kdex in keywords.index:
                    kw2 = keywords.at[kdex,'Keyword']
                    if kw2 in words:
                        df.at[w,'Subject'] = keywords.at[kdex,'Subject']
                        break
                    else: continue
df.rename(columns={'Min':'Location','Max':'CourseLength'}, inplace=True)

df.to_csv("outtie5000.csv")
df

C:\Users\qf3636ll\AppData\Local\Temp\ipykernel_23404\1600636705.py:68: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 12 hr' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.at[i,'Max'] = r_length
C:\Users\qf3636ll\AppData\Local\Temp\ipykernel_23404\1600636705.py:111: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '(mapleton, fd)' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.at[i, 'Min'] = loc_name
C:\Users\qf3636ll\AppData\Local\Temp\ipykernel_23404\1600636705.py:212: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'FIRE/EMT' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.at[w,'Subject'] = keywords.at[kdex,'Subject']

,Start Date,End Date,Item Name,Status,Location,CourseLength,Enrolled,instructor,starttime,endtime,length,Subject
0,3/26/2022,3/27/2022,2022 fire school: full conference,Active,1.0,12hr,177,na,8:00 AM,5:00 PM,9,FIRE/EMT
1,3/25/2023,3/26/2023,2023 fire school: full conference,Active,1.0,12hr,179,na,8:00 AM,4:00 PM,8,FIRE/EMT
2,3/26/2022,3/27/2022,2022 fire school: mini conference,Active,1.0,4-8hr,80,na,8:00 AM,5:00 PM,9,FIRE/EMT
3,3/25/2023,3/26/2023,2023 fire school: mini conference,Active,1.0,4-8hr,124,na,8:00 AM,4:00 PM,8,FIRE/EMT
4,4/4/2020,4/5/2020,2020 fire school: full conference,Active,1.0,12hr,0,na,8:00 AM,5:00 PM,9,FIRE/EMT
...,...,...,...,...,...,...,...,...,...,...,...,...
1649,6/2/2021,7/2/2021,trained medication aide,Inactive,(riverland owatonna campus),nahr__,0,na,na,na,na,NURSING
1650,1/10/2022,2/7/2022,trained medication aide,Inactive,(riverland owatonna campus),nahr__,0,na,na,na,na,NURSING
1651,11/2/2022,12/2/2022,trained medication aide,Inactive,(riverland owatonna campus),nahr__,0,na,na,na,na,NURSING
1652,9/8/2022,9/8/2022,trained medication aide refresher,Inactive,(riverland albert lea campus),nahr__,0,na,na,na,na,NURSING
1653,1/8/2020,2/4/2020,welding,Active,1.0,160hr,8,na,na,na,na,INDUSTRY